[platformio]
default_envs = esp32-c3-devkitm-1
src_dir = firmware
include_dir = include

[env:esp32-c3-devkitm-1]
platform = espressif32@6.12.0
board = esp32-c3-devkitm-1
framework = arduino
custom_rust_features = esp32c3,wifi,bluetooth
build_src_filter = +<*.cpp> -<arduino/> -<simulator/>
board_build.partitions = partitions.csv
extra_scripts =
    pre:scripts/build_rust.py
    post:scripts/merge_firmware.py
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -Os
    -ffunction-sections
    -fdata-sections
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DRUSTSCRIPT_SD_CS=7

[env:arduino]
platform = native@1.2.1
build_src_filter =
    +<arduino/main.cpp>
    +<simulator/arduino_sim.cpp>
extra_scripts = pre:scripts/build_arduino.py
custom_rust_target = x86_64-unknown-linux-gnu
build_flags =
    -std=gnu++17
    -Ifirmware/simulator/include

[env:esp32s31]
platform = native@1.2.1
build_src_filter = +<esp32s31/stub.cpp>
extra_scripts = pre:scripts/build_esp32s31.py
custom_rust_features = esp32s31,wifi,bluetooth
